# playbook.yml
---
-
  hosts: all
  sudo: True


  pre_tasks:
    - name: update apt cache
      sudo: yes
      apt: update_cache=yes cache_valid_time=3600
      sudo_user: root

  roles:
    - webserver
    - database
    - project
