# profiling.yml
---
- hosts: all

  sudo: true

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes

  roles:
    - general
    - webserver
    - memcached
    - database
    - profiling
    - bodeboca
