---
- name: Assures {{ project_document_root }}/htdocs dir exists
  file: path={{ project_document_root }}/htdocs state=directory
- name: Copy file
  template:
    src: code.htdocs.j2
    dest: "{{ project_document_root }}/htdocs/code.htdocs"

- name: Assures {{ project_document_root }}/logs dir exists
  file: path={{ project_document_root }}/logs state=directory
- name: Copy file
  template:
    src: code.htdocs.j2
    dest: "{{ project_document_root }}/logs/code.htdocs"

- name: Copy across new virtual host (project)
  template:
    src=project.conf.j2
    dest=/etc/apache2/sites-available/project.conf
  notify:
    - reload apache

- name: Enable new project virtual host
  file:
    src=/etc/apache2/sites-available/project.conf
    dest=/etc/apache2/sites-enabled/project.conf
    state=link
  notify:
    - reload apache




- name: Make sure {{ project_document_root }}/htdocs is owned by www-data
  action: file path={{ project_document_root }}/htdocs owner=www-data group=www-data

- name: Make sure {{ project_document_root }}/logs is owned by www-data
  action: file path={{ project_document_root }}/logs owner=www-data group=www-data

- name: Add the virtualhosts to the file /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1 {{item.server_name}}"
  sudo: yes
  with_items: vhosts
