---
# - name: Install XHProf PECL extension
#   shell: pecl install --soft xhprof-beta
#   ignore_errors: true
#   tags: profiling

# Install and configure XHProf.
- name: Install XHProf using PECL.
  command: "pecl install {{ item }}"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  with_items:
    # Manual channel installation required for certain PEAR versions.
    - "channel://pecl.php.net/xhprof-0.9.4"
    - xhprof

- name: Create extension ini file in mods-available # echo "extension=xhprof.so > xhprof.ini"
  copy: src=php/mods-available/xhprof.ini dest=/etc/php5/mods-available/ owner=root mode=0644
  tags: profiling

- name: Enable module
  shell: php5enmod xhprof
  notify: restart apache
  tags: profiling
