---
# - name: Install xdebug PECL extension
#   shell: pecl install --soft xdebug
#   ignore_errors: true
#   tags: profiling


# Install and configure XHProf.
- name: Install xdebug using PECL.
  command: "pecl install {{ item }}"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  with_items:
    # # Manual channel installation required for certain PEAR versions.
    # - "channel://pecl.php.net/xdebug-0.9.4"
    - xdebug

- name: Create extension ini file in mods-available
  copy: src=php/mods-available/xdebug.ini dest=/etc/php5/mods-available/ owner=root mode=644
  tags: profiling

- name: Enable module
  shell: php5enmod xdebug
  notify: restart apache
  tags: profiling
